"""
True Biopython RMSD matrix calculator.

This version uses Bio.PDB.PDBParser to parse each frame and builds an all-vs-all
RMSD matrix for frames separated by END records in the input PDB trajectory.

PowerShell usage (copy one scenario at a time):

Scenario 1: Change into the script directory.
    Set-Location "C:\\Users\\yagd9\\Documents\\Stony Brook AI Drug Discovery\\Github\\Pymol\\AI for Drug Discovery Project\\simple_RMSD"

Scenario 2: Basic run using your own PDB (CSV is written next to input file).
    & "c:/Users/yagd9/Documents/Stony Brook AI Drug Discovery/Github/Pymol/AI for Drug Discovery Project/.venv/Scripts/python.exe" .\\calculate_rmsd_biopython_true.py -i "C:\\Path\\To\\your_frames.pdb"

Scenario 3: Custom output directory and CSV file name.
    & "c:/Users/yagd9/Documents/Stony Brook AI Drug Discovery/Github/Pymol/AI for Drug Discovery Project/.venv/Scripts/python.exe" .\\calculate_rmsd_biopython_true.py -i "C:\\Path\\To\\your_frames.pdb" -o "C:\\Path\\To\\results" --output-name "team_rmsd.csv"

Scenario 4: Backbone-only RMSD and limit to first 500 frames.
    & "c:/Users/yagd9/Documents/Stony Brook AI Drug Discovery/Github/Pymol/AI for Drug Discovery Project/.venv/Scripts/python.exe" .\\calculate_rmsd_biopython_true.py -i "C:\\Path\\To\\your_frames.pdb" --atom-scope backbone --max-frames 500

Scenario 5: Show command help and all arguments.
    & "c:/Users/yagd9/Documents/Stony Brook AI Drug Discovery/Github/Pymol/AI for Drug Discovery Project/.venv/Scripts/python.exe" .\\calculate_rmsd_biopython_true.py --help

Important path note for teams cloning from GitHub:
    Your local folder path will likely be different from the example paths in
    this header. Replace script, Python, input, and output paths with your own
    machine-specific paths before running the commands.

If your team has a working python command on PATH, you may replace the long
venv python path with "python".
"""
### Disclaimer: Generative AI was used in the development of 
# this file. The code was generated by an AI model 
# and may require review and testing to 
# ensure correctness and suitability for your specific use case.
# the Researcher takes full responsibility for the use of this code 
# and any consequences that may arise from its use.

import argparse
import csv
import sys
from io import StringIO
from pathlib import Path

import numpy as np
from Bio.PDB import PDBParser


BACKBONE_ATOM_NAMES = {"N", "CA", "C", "O", "OXT"}


def parse_args():
    """Define and parse CLI arguments for portable, team-friendly execution."""
    parser = argparse.ArgumentParser(
        description="Compute all-vs-all RMSD matrix using Biopython parsing.",
        epilog=(
            "Examples:\n"
            "  python calculate_rmsd_biopython_true.py -i C:/data/frames.pdb\n"
            "  python calculate_rmsd_biopython_true.py -i C:/data/frames.pdb -o C:/out --output-name team_rmsd.csv --atom-scope backbone"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--input",
        "-i",
        type=Path,
        required=True,
        help="Input PDB file with multiple frames separated by END records.",
    )
    parser.add_argument(
        "--output-dir",
        "-o",
        type=Path,
        default=None,
        help="Directory for output CSV (defaults to input file directory).",
    )
    parser.add_argument(
        "--output-name",
        default=None,
        help="Output CSV file name (defaults to <input_stem>_rmsd_matrix.csv).",
    )
    parser.add_argument(
        "--max-frames",
        type=int,
        default=None,
        help="Optional: only process the first N frames.",
    )
    parser.add_argument(
        "--atom-scope",
        choices=["full", "backbone"],
        default="full",
        help="Atom selection scope for RMSD: full or backbone.",
    )
    return parser.parse_args()


def split_frames_from_pdb(pdb_file):
    """
    Split a multi-frame PDB trajectory text file into per-frame PDB strings.

    Frames are detected primarily by END records. Supported record types are
    filtered so each frame can be parsed cleanly by Biopython.
    """
    frames = []
    current = []

    with open(pdb_file, "r", encoding="utf-8", errors="ignore") as handle:
        for line in handle:
            # END marks frame boundaries in many trajectory-exported PDB files.
            if line.startswith("END"):
                if current:
                    frames.append("".join(current + ["END\n"]))
                    current = []
                continue

            # Keep commonly useful PDB records and discard unrelated lines.
            if line.startswith(("ATOM", "HETATM", "TER", "CRYST1", "HEADER", "REMARK", "TITLE", "MODEL", "ENDMDL", "SEQRES", "COMPND")):
                current.append(line)

    if current:
        frames.append("".join(current + ["END\n"]))

    if len(frames) < 2:
        raise ValueError("Need at least 2 frames in the input PDB.")

    return frames


def atom_key(atom):
    """Build a stable, sortable atom identity key across frames."""
    residue = atom.get_parent()
    chain = residue.get_parent() if residue is not None else None
    residue_id = residue.get_id() if residue is not None else ("", 0, "")
    return (
        chain.get_id() if chain is not None else "",
        residue.get_resname() if residue is not None else "",
        residue_id[0],
        residue_id[1],
        residue_id[2],
        atom.get_name(),
        atom.get_altloc() or "",
    )


def parse_frame_with_biopython(frame_text, frame_index, parser, atom_scope):
    """
    Parse one frame and return atom keys plus coordinates.

    Atom ordering is normalized via sorting by atom_key so frame-to-frame
    comparisons stay consistent even if source ordering differs.
    """
    structure = parser.get_structure(f"frame_{frame_index}", StringIO(frame_text))
    model = next(structure.get_models())

    atoms = []
    for atom in model.get_atoms():
        if atom_scope == "backbone" and atom.get_name().strip() not in BACKBONE_ATOM_NAMES:
            continue
        atoms.append(atom)
    if not atoms:
        raise ValueError(f"Frame {frame_index} has no atoms.")

    # Deterministic ordering is critical for valid all-vs-all RMSD which compares
    # all frames to one another to calculate the RMSD.
    atoms_sorted = sorted(atoms, key=atom_key)
    keys = [atom_key(a) for a in atoms_sorted]
    coords = np.array([a.get_coord() for a in atoms_sorted], dtype=np.float64)
    return keys, coords


def build_coordinate_tensor(frames_parsed):
    """
    Convert parsed frames into a dense 2D tensor for vectorized RMSD math.

    Returns:
    - vectors: shape (num_frames, num_atoms * 3)
    - atom_count: number of atoms per frame used in RMSD normalization
    """
    ref_keys, _ = frames_parsed[0]
    atom_count = len(ref_keys)
    frame_count = len(frames_parsed)

    vectors = np.empty((frame_count, atom_count * 3), dtype=np.float64)

    for i, (keys, coords) in enumerate(frames_parsed):
        if len(keys) != atom_count:
            raise ValueError(
                f"Frame {i + 1} atom count mismatch: {len(keys)} vs {atom_count}"
            )

        if keys == ref_keys:
            vectors[i, :] = coords.reshape(-1)
            continue

        # If atom order differs, remap by key to align to the reference frame.
        key_to_coord = {k: c for k, c in zip(keys, coords)}
        try:
            aligned = np.array([key_to_coord[k] for k in ref_keys], dtype=np.float64)
        except KeyError as exc:
            raise ValueError(
                f"Frame {i + 1} missing atom key {exc}."
            ) from exc
        vectors[i, :] = aligned.reshape(-1)

    return vectors, atom_count


def compute_rmsd_matrix(frames_parsed):
    """
    Compute full all-vs-all RMSD matrix with vectorized linear algebra.

    Uses identity:
        ||a - b||^2 = ||a||^2 + ||b||^2 - 2(a . b)
    then divides by atom_count and square-roots to obtain RMSD.
    """
    vectors, atom_count = build_coordinate_tensor(frames_parsed)
    sq_norms = np.einsum("ij,ij->i", vectors, vectors)
    gram = vectors @ vectors.T
    msd = (sq_norms[:, None] + sq_norms[None, :] - 2.0 * gram) / float(atom_count)
    msd = np.maximum(msd, 0.0)
    return np.sqrt(msd)


def write_rmsd_csv(rmsd_matrix, output_csv):
    """Write RMSD matrix to CSV with Frame labels for rows and columns."""
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    n = rmsd_matrix.shape[0]
    headers = ["Frame"] + [f"Frame{j}" for j in range(1, n + 1)]

    with open(output_csv, "w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(headers)
        for i in range(n):
            row = [str(i + 1)] + [f"{x:.6f}" for x in rmsd_matrix[i]]
            writer.writerow(row)


def main():
    """Orchestrate CLI parsing, frame parsing, RMSD computation, and CSV export."""
    args = parse_args()

    atom_scope = args.atom_scope
    input_path = args.input.expanduser()

    if not input_path.exists():
        print(f"Error: input file not found: {input_path}")
        sys.exit(1)

    # Portable defaults:
    # - output directory defaults to input PDB directory
    # - output filename defaults to <input_stem>_rmsd_matrix.csv
    output_dir = args.output_dir.expanduser() if args.output_dir else input_path.parent
    output_name = args.output_name or f"{input_path.stem}_rmsd_matrix.csv"

    print(f"Reading PDB file: {input_path}")
    frames = split_frames_from_pdb(input_path)

    if args.max_frames is not None:
        frames = frames[: args.max_frames]

    print(f"Frames to process: {len(frames)}")
    print(f"Atom scope: {atom_scope}")

    parser = PDBParser(QUIET=True)
    parsed = []
    total = len(frames)
    for idx, frame_text in enumerate(frames, start=1):
        parsed.append(parse_frame_with_biopython(frame_text, idx, parser, atom_scope))
        if idx % 100 == 0 or idx == total:
            print(f"Parsed {idx}/{total} frames")

    print("Computing RMSD matrix...")
    rmsd_matrix = compute_rmsd_matrix(parsed)

    output_csv = output_dir / output_name
    print(f"Writing RMSD matrix to: {output_csv}")
    write_rmsd_csv(rmsd_matrix, output_csv)
    print("Done.")


if __name__ == "__main__":
    main()
